# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 sw=2 expandtab:

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  box = "ubuntu/trusty64"

  config.vm.define :trusty64 do |trusty64|
    trusty64.vm.box = box
    trusty64.vm.network "private_network", ip: "10.0.0.2"
    #centos65.vm.network :forwarded_port, guest: 22, host: 2201, id: "ssh", auto_correct: true
    trusty64.vm.hostname = "trusty64"

    # Increased Memory required for compiling boost with gcc 4.8  
    config.vm.provider "virtualbox" do |v|  
      v.memory = 1536
    end
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1536"] 
      vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate//git", "1"]  
    end

    ## load the salt folder
    trusty64.vm.synced_folder "salt/roots/", "/srv/"
    ## load install scripts
    trusty64.vm.synced_folder "../scripts", "/srv/scripts/"
    
    # provision
    trusty64.vm.provision :salt do |salt|
      salt.minion_config = "salt/minion"
      salt.run_highstate = true
    end

  end
  
end

